name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-publish:
    runs-on: ubuntu-latest
    environment: bobcasino
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PAT }}
          OAUTH1: ${{ secrets.OAUTH}}
          USER1: ${{ vars.USERNAME}}
          CHANNELS: ${{ vars.CHANNELS}}
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t ghcr.io/whoknowsai/bobcasino:latest .
          docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ghcr.io/whoknowsai/bobcasino:latest